"""Generate the reference pages of the documentation site from the code.

Each page here is derived from the object it documents - the configuration
model, the admin routes and their role rules, the MCP tool list, the connector
registry, the role-condition vocabulary, the feature-status registry and the
Makefile - so the reference cannot drift from the code without this tool
noticing.

    uv run python tools/docs/generate.py --write   # regenerate
    uv run python tools/docs/generate.py --check   # fail if anything is stale

Output is deterministic. The configuration is built from defaults only: every
`INTERLOCK_*` and `ONYX_*` variable is removed from the environment first, and
no YAML file is read, so a developer's local settings never reach the docs.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT / "docs-site"
DOCS = SITE / "src" / "content" / "docs"

for _name in list(os.environ):
    if _name.startswith(("INTERLOCK_", "ONYX_")):
        del os.environ[_name]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from pydantic import BaseModel  # noqa: E402

GENERATOR = "tools/docs/generate.py"


def _md_frontmatter(title: str, description: str, source: str, extra: str = "") -> str:
    """Markdown pages carry the banner as an HTML comment, which MDX would reject."""
    return (
        "---\n"
        f"title: {json.dumps(title)}\n"
        f"description: {json.dumps(description)}\n"
        "generated: true\n"
        f"{extra}"
        "---\n\n"
        f"<!-- Generated by {GENERATOR} from {source}. Do not edit by hand. -->\n\n"
    )


def _cell(value: object) -> str:
    text = str(value).replace("|", "\\|").replace("\n", " ")
    return text if text else " "


def _table(headers: Iterable[str], rows: Iterable[Iterable[object]]) -> str:
    headers = list(headers)
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(_cell(v) for v in row) + " |" for row in rows]
    return "\n".join(out) + "\n"


def _code(value: object) -> str:
    return f"`{value}`" if value not in ("", None) else " "


# --- configuration ------------------------------------------------------------


def _default_repr(value: object) -> str:
    if value is None:
        return "unset"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, dict)):
        return json.dumps(value)
    if value == "":
        return '""'
    return str(value)


def _type_name(annotation: object) -> str:
    text = getattr(annotation, "__name__", None) or str(annotation)
    text = text.replace("typing.", "")
    return re.sub(r"<class '([^']+)'>", r"\1", text)


def configuration_page() -> str:
    from interlock.config import InterLockConfig

    config = InterLockConfig()
    parts = [
        _md_frontmatter(
            "Configuration",
            "Every InterLock setting, its environment variable, default and meaning.",
            "src/interlock/config.py",
        ),
        "Settings are read, in increasing precedence, from the defaults below, a "
        "YAML file (`config.yaml`, or the path in `INTERLOCK_CONFIG_PATH`), and "
        "environment variables. A nested key `section.key` is the environment "
        "variable `INTERLOCK_SECTION__KEY`. Unknown keys are rejected at start.\n\n",
    ]
    top_level: list[list[object]] = []
    sections: list[tuple[str, type[BaseModel], BaseModel]] = []
    for name, field in InterLockConfig.model_fields.items():
        annotation = field.annotation
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            sections.append((name, annotation, getattr(config, name)))
        else:
            top_level.append(
                [
                    _code(name),
                    _code(f"INTERLOCK_{name.upper()}"),
                    _code(_default_repr(getattr(config, name))),
                    field.description or "",
                ]
            )
    parts.append("## Top level\n\n")
    parts.append(_table(["Key", "Environment variable", "Default", "Meaning"], top_level))
    for section, model, value in sections:
        parts.append(f"\n## `{section}`\n\n")
        section_field = InterLockConfig.model_fields[section]
        if section_field.description:
            parts.append(section_field.description + "\n\n")
        rows: list[list[object]] = []
        for name, field in model.model_fields.items():
            annotation = field.annotation
            if isinstance(annotation, type) and issubclass(annotation, BaseModel):
                nested = getattr(value, name)
                for sub, subfield in annotation.model_fields.items():
                    rows.append(
                        [
                            _code(f"{section}.{name}.{sub}"),
                            _code(f"INTERLOCK_{section.upper()}__{name.upper()}__{sub.upper()}"),
                            _code(_default_repr(getattr(nested, sub))),
                            subfield.description or "",
                        ]
                    )
                continue
            rows.append(
                [
                    _code(f"{section}.{name}"),
                    _code(f"INTERLOCK_{section.upper()}__{name.upper()}"),
                    _code(_default_repr(getattr(value, name))),
                    field.description or "",
                ]
            )
        parts.append(_table(["Key", "Environment variable", "Default", "Meaning"], rows))
    return "".join(parts)


# --- admin API and roles -----------------------------------------------------

ROLE_MEANINGS = {
    "owner": "Everything, including admin accounts. The first admin is an owner.",
    "admin": "Everything, like owner.",
    "security_admin": "Identities, keys and grants; any mutation without a narrower rule.",
    "source_admin": "Data sources, connectors, source roles, catalog and ingestion.",
    "policy_admin": "Policy rules.",
    "approval_reviewer": "Reviewing queued writes: approve and reject.",
    "auditor": "Read-only access to the console, audit and usage.",
}


def _admin_app() -> Any:
    from interlock.admin.app import create_app
    from interlock.config import InterLockConfig

    config = InterLockConfig()
    config.admin.secret_key = "documentation-generator-only-key-not-used"
    return create_app(config=config)


def _admin_routes() -> list[tuple[str, str, str, str]]:
    """(path, method, summary, tag) for every documented admin route."""
    app = _admin_app()
    rows = []
    for route in app.routes:
        path = getattr(route, "path", "")
        methods = sorted((getattr(route, "methods", None) or set()) - {"HEAD", "OPTIONS"})
        if not path or not methods or path.startswith("/static"):
            continue
        if not getattr(route, "include_in_schema", True):
            continue
        endpoint = getattr(route, "endpoint", None)
        doc = (getattr(endpoint, "__doc__", None) or "").strip().splitlines()
        summary = doc[0].strip() if doc else ""
        tag = path.strip("/").split("/")[0] or "root"
        for method in methods:
            rows.append((path, method, summary, tag))
    return sorted(set(rows))


def _roles_cell(path: str, method: str) -> str:
    from interlock.admin.auth_middleware import required_roles

    public = ("/health", "/ready", "/auth/login", "/auth/oidc", "/auth/csrf")
    if path in public or any(path.startswith(p + "/") for p in public):
        return "public"
    roles = required_roles(path, method)
    if roles is None:
        return "any signed-in admin"
    return ", ".join(["owner", "admin", *sorted(roles)])


def admin_api_page() -> str:
    rows = _admin_routes()
    parts = [
        _md_frontmatter(
            "Admin API",
            "Every admin route, the roles that may call it, and the OpenAPI document.",
            "the admin application's routes and auth_middleware.required_roles()",
        ),
        "The console and its JSON API share one server. Every route except the "
        "public ones needs a signed-in admin session; `POST`, `PUT`, `PATCH` and "
        "`DELETE` also need the `X-CSRF-Token` header from `GET /auth/csrf`. The "
        "machine-readable description is [openapi.json](/admin-api/openapi.json).\n\n",
    ]
    tags: dict[str, list[tuple[str, str, str, str]]] = {}
    for row in rows:
        tags.setdefault(row[3], []).append(row)
    for tag in sorted(tags):
        parts.append(f"## `/{tag}`\n\n")
        parts.append(
            _table(
                ["Method", "Path", "Roles", "Summary"],
                [
                    [method, _code(path), _roles_cell(path, method), summary]
                    for path, method, summary, _ in tags[tag]
                ],
            )
        )
        parts.append("\n")
    return "".join(parts).rstrip("\n") + "\n"


def admin_openapi() -> str:
    spec = _admin_app().openapi()
    return json.dumps(spec, indent=2, sort_keys=True) + "\n"


def admin_roles_page() -> str:
    from interlock.admin.auth_middleware import _ADMIN_MUTATION_RULES, _ADMIN_READ_RULES

    parts = [
        _md_frontmatter(
            "Admin roles",
            "The admin roles, what each may do, and which routes need which role.",
            "src/interlock/admin/auth_middleware.py",
        ),
        "An admin account holds one or more roles. `owner` and `admin` may do "
        "everything; the others open parts of the console. A request is allowed "
        "when the account holds any role the route's rule names.\n\n",
        _table(["Role", "Meaning"], [[_code(r), m] for r, m in ROLE_MEANINGS.items()]),
        "\n## Reading\n\n",
        _table(
            ["Path prefix", "Roles besides owner and admin"],
            [[_code(p), ", ".join(sorted(r))] for p, r in _ADMIN_READ_RULES],
        ),
        "\n## Changing\n\n",
        "Rules for `POST`, `PUT`, `PATCH` and `DELETE`. A change under `/dashboard` "
        "or `/api` with no rule below needs `security_admin`.\n\n",
        _table(
            ["Path prefix", "Roles besides owner and admin"],
            [[_code(p), ", ".join(sorted(r))] for p, r in _ADMIN_MUTATION_RULES],
        ),
    ]
    return "".join(parts)


# --- MCP tools ---------------------------------------------------------------


def mcp_tools_page() -> str:
    from interlock.gateway.mcp_adapter import MCP_TOOLS

    parts = [
        _md_frontmatter(
            "MCP tools",
            "The tools the gateway's /mcp endpoint offers, and their arguments.",
            "interlock.gateway.mcp_adapter.MCP_TOOLS",
        ),
        "Every tool call is authenticated, authorized by source roles, shaped by "
        "policy, redacted and audited, exactly like a query on any other "
        "protocol. Tools named `agentgate_*` are deprecated aliases of the "
        "`interlock_*` tools, kept until `1.2.0`.\n\n",
    ]
    for tool in sorted(MCP_TOOLS, key=lambda t: str(t["name"])):
        name = str(tool["name"])
        if name.startswith("agentgate_"):
            continue
        schema = tool.get("inputSchema") or {}
        required = set(schema.get("required") or [])
        props = schema.get("properties") or {}
        parts.append(f"## `{name}`\n\n{tool.get('description', '')}\n\n")
        if props:
            parts.append(
                _table(
                    ["Argument", "Type", "Required", "Meaning"],
                    [
                        [
                            _code(arg),
                            spec.get("type", ""),
                            "yes" if arg in required else "no",
                            spec.get("description", ""),
                        ]
                        for arg, spec in sorted(props.items())
                    ],
                )
            )
            parts.append("\n")
    return "".join(parts).rstrip("\n") + "\n"


# --- connectors --------------------------------------------------------------


def _connector_rows() -> list[Any]:
    from interlock.connections.connectors import CONNECTOR_DEFINITIONS

    return sorted(CONNECTOR_DEFINITIONS.values(), key=lambda d: d.key)


def connectors_index_page() -> str:
    from interlock.connections.activation import DEFAULT_ACTIVE_CONNECTOR_KEYS
    from interlock.feature_status import GOVERNANCE_UNVERIFIED_CONNECTORS

    parts = [
        _md_frontmatter(
            "Connectors",
            "Every connector in the registry: its status, and whether it starts active.",
            "interlock.connections.connectors.CONNECTOR_DEFINITIONS",
            extra="sidebar:\n  order: 0\n",
        ),
        "A source is registered on a connector. `planned` connectors have no "
        "working adapter and can never be activated. A fresh deployment starts "
        "with the connectors marked *active by default*; a source admin can "
        "activate others from the Connectors page.\n\n",
    ]
    if (DOCS / "reference" / "connector-support-matrix.md").exists():
        parts.append(
            "What each status means, and what has been certified, is in the "
            "[connector support matrix](/reference/connector-support-matrix/).\n\n"
        )
    rows = []
    for d in _connector_rows():
        notes = []
        if d.key in GOVERNANCE_UNVERIFIED_CONNECTORS:
            notes.append("governance not exercised by any test stack")
        rows.append(
            [
                f"[{d.name}](/reference/connectors/{d.key}/)",
                _code(d.key),
                d.status,
                "yes" if d.key in DEFAULT_ACTIVE_CONNECTOR_KEYS else "no",
                "; ".join(notes),
            ]
        )
    parts.append(_table(["Connector", "Key", "Status", "Active by default", "Note"], rows))
    return "".join(parts)


def connector_page(d: Any) -> str:
    from interlock.connections.activation import DEFAULT_ACTIVE_CONNECTOR_KEYS
    from interlock.feature_status import GOVERNANCE_UNVERIFIED_CONNECTORS

    caps = {k: v for k, v in vars_of(d.capabilities).items() if v}
    parts = [
        _md_frontmatter(
            d.name,
            f"The {d.name} connector: configuration keys, capabilities and role templates.",
            f"CONNECTOR_DEFINITIONS[{d.key!r}]",
        ),
        f"{d.description}\n\n",
        _table(
            ["Property", "Value"],
            [
                ["Key", _code(d.key)],
                ["Source type", _code(d.source_type)],
                ["Status", d.status],
                ["Active by default", "yes" if d.key in DEFAULT_ACTIVE_CONNECTOR_KEYS else "no"],
                ["Default cache strategy", _code(d.default_cache_strategy)],
                ["Capabilities", ", ".join(sorted(caps)) or "none"],
            ],
        ),
    ]
    if d.key in GOVERNANCE_UNVERIFIED_CONNECTORS:
        parts.append(
            "\n:::caution\nNo test stack registers a source on this connector, so its "
            "source roles, policy, redaction and audit are not exercised by any test. "
            "The adapter works; its governance is unproven.\n:::\n"
        )
    if d.credential_fields or d.secret_fields:
        parts.append("\n## Connection configuration\n\n")
        parts.append(
            "Secret fields should be given as a reference, `<field>_ref`, such as "
            "`env://NAME`, rather than a literal.\n\n"
        )
        rows = [[_code(f), "no"] for f in d.credential_fields]
        rows += [[_code(f), f"yes; prefer {_code(f + '_ref')}"] for f in d.secret_fields]
        parts.append(_table(["Key", "Secret"], rows))
    if d.role_templates:
        parts.append("\n## Default role templates\n\n")
        parts.append("Offered when a source is created with default roles. Edit them to fit.\n\n")
        for role in sorted(d.role_templates):
            parts.append(f"### `{role}`\n\n")
            parts.append(
                _table(
                    ["Effect", "Action", "Resource type", "Pattern"],
                    [
                        [
                            s.get("effect", ""),
                            _code(s.get("action", "")),
                            _code(s.get("resource_type", "")),
                            _code(s.get("resource_pattern", "")),
                        ]
                        for s in d.role_templates[role]
                    ],
                )
            )
            parts.append("\n")
    return "".join(parts).rstrip("\n") + "\n"


def vars_of(obj: Any) -> dict[str, Any]:
    from dataclasses import asdict

    return asdict(obj)


# --- role conditions ---------------------------------------------------------


def role_conditions_page() -> str:
    from interlock.connections.role_vocabulary import constraint_specs

    parts = [
        _md_frontmatter(
            "Role conditions",
            "Conditions a source-role statement can carry, and their types.",
            "interlock.connections.role_vocabulary.constraint_specs()",
        ),
        "A statement's conditions narrow what it matches. Each connector offers "
        "the subset that applies to its actions; the role editor shows only "
        "those. On a `deny` statement a condition that can never be satisfied is "
        "refused at save, because the guardrail would silently never fire.\n\n",
        _table(
            ["Condition", "Type", "Choices", "Meaning"],
            [
                [
                    _code(s.key),
                    s.type,
                    ", ".join(_code(c) for c in s.choices) or " ",
                    s.help or s.label,
                ]
                for s in constraint_specs()
            ],
        ),
    ]
    return "".join(parts)


# --- feature status ----------------------------------------------------------


def feature_status_page() -> str:
    from interlock.feature_status import FEATURE_STATUSES

    labels = {"stable": "Stable", "beta": "Beta", "disabled": "Disabled", "planned": "Planned"}

    def state(f: Any) -> str:
        return f"`{labels.get(f.state, f.state)}`"

    enabled = [f for f in FEATURE_STATUSES if f.public_beta]
    held = [f for f in FEATURE_STATUSES if not f.public_beta]
    parts = [
        _md_frontmatter(
            "Feature status",
            "What is beta, disabled or planned, with the evidence and limitation for each.",
            "src/interlock/feature_status.py",
        ),
        "This page is the public-beta honesty contract. A capability is shown as "
        "enabled in the console, the README or these docs only if it is listed "
        "under current capabilities here with matching evidence. Anything listed "
        "as `Disabled` or `Planned` stays hidden, appears disabled, or is labelled "
        "as not part of the public beta. The console reads the same registry, so "
        "the two cannot disagree.\n\n",
        "## Status legend\n\n",
        "- `Certified`: local compose or equivalent certification is repeatable.\n"
        "- `Beta`: implemented and test-covered, but needs broader certification "
        "before stronger claims.\n"
        "- `Disabled`: code or configuration may exist, but the capability is not "
        "enabled for public beta.\n"
        "- `Planned`: modeled or documented, but not wired or certified enough to "
        "expose as active functionality.\n\n",
        "## Current Public-Beta Capabilities\n\n",
        _table(
            ["Feature", "Status", "Evidence", "Public-Beta Limitation"],
            [[f.label, state(f), f.evidence, f.limitation or " "] for f in enabled],
        ),
        "\n## Disabled Or Planned Capabilities\n\n",
        _table(
            ["Feature", "Status", "Why It Is Not Public-Beta Enabled"],
            [
                [f.label, state(f), " ".join(x for x in (f.evidence, f.limitation) if x)]
                for f in held
            ],
        ),
        CODE_NOT_ON_REQUEST_PATH,
    ]
    return "".join(parts)


CODE_NOT_ON_REQUEST_PATH = """
## Code Present But Not On The Request Path

These modules are implemented and unit-tested but nothing in the live request
path imports them. They are kept because the tests still pass and the designs
are the starting point for the corresponding `Planned` capabilities above - not
because they run. Do not read them as a description of current behavior.

| Module | Relates to |
|---|---|
| `cache/qdrant_index.py` | Qdrant vector backend (`Planned`) |
| `core/intent.py` | Semantic cache serving (`Disabled`) |
| `core/opa.py` | External policy engine (not a public-beta capability) |
| `discovery/classifier.py`, `discovery/enrichment.py`, `discovery/entity_resolver.py` | Automatic category classifier and entity enrichment (`Planned`) |
| `worker/chunker.py`, `worker/chunk_indexer.py` | Chunk-level discovery indexing (`Planned`) |
| `pipeline/runtime.py` | Shared pipeline abstraction; protocol adapters still hold their own copies |
| `db/pubsub.py` | Superseded by `db/notify.py` on the live path |
| `utils/profiler.py`, `utils/security.py` | Developer tooling, not runtime |

## Release Rule

If a feature moves from `Planned` or `Disabled` to `Beta` or `Certified`, update
`src/interlock/feature_status.py`, the connector and support pages where they
apply, and the relevant tests in the same change; this page is regenerated from
the registry. If a feature is exposed in the console while still planned, the
console must disable the control or label it as planned.
"""


# --- make targets ------------------------------------------------------------


def make_targets_page() -> str:
    makefile = (ROOT / "Makefile").read_text()
    rows = []
    for line in makefile.splitlines():
        match = re.match(r'\s*@echo "  ([a-z0-9-]+)\s+(.*)"\s*$', line)
        if match:
            rows.append([_code(f"make {match.group(1)}"), match.group(2).strip()])
    parts = [
        _md_frontmatter(
            "Make targets",
            "The development, test and release targets in the Makefile.",
            "the Makefile's help text",
        ),
        "Run `make help` for the same list.\n\n",
        _table(["Target", "What it does"], rows),
    ]
    return "".join(parts)


# --- codebase map ------------------------------------------------------------


def codebase_map_page() -> str:
    import ast

    package_root = ROOT / "src" / "interlock"
    rows = []
    for init in sorted(package_root.glob("*/__init__.py")):
        tree = ast.parse(init.read_text(encoding="utf-8"))
        doc = (ast.get_docstring(tree) or "").strip().splitlines()
        rows.append([_code(f"interlock.{init.parent.name}"), doc[0] if doc else ""])
    parts = [
        _md_frontmatter(
            "Codebase map",
            "The Python packages under src/interlock and what each one is for.",
            "each package's docstring",
            extra="sidebar:\n  order: 3\n",
        ),
        "The runtime is one Python package, `interlock`, with the services as "
        "entry points (`python -m interlock.gateway`, `.admin`, `.worker`). "
        "Database migrations are in `migrations/`, the Helm chart and deployment "
        "scripts in `deploy/`, tests in `tests/`, and this site in `docs-site/`.\n\n",
        _table(["Package", "What it holds"], rows),
    ]
    return "".join(parts)


# --- driver --------------------------------------------------------------------


def outputs() -> dict[Path, Callable[[], str]]:
    reference = DOCS / "reference"
    files: dict[Path, Callable[[], str]] = {
        reference / "configuration.md": configuration_page,
        reference / "admin-api.md": admin_api_page,
        SITE / "public" / "admin-api" / "openapi.json": admin_openapi,
        reference / "admin-roles.md": admin_roles_page,
        reference / "mcp-tools.md": mcp_tools_page,
        reference / "connectors" / "index.md": connectors_index_page,
        reference / "role-conditions.md": role_conditions_page,
        reference / "feature-status.md": feature_status_page,
        reference / "make-targets.md": make_targets_page,
        DOCS / "project" / "codebase-map.md": codebase_map_page,
    }
    for d in _connector_rows():
        files[reference / "connectors" / f"{d.key}.md"] = lambda d=d: connector_page(d)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    expected = outputs()
    for path, render in sorted(expected.items()):
        content = render()
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    # A connector removed from the registry must not leave its page behind.
    connectors_dir = DOCS / "reference" / "connectors"
    if connectors_dir.exists():
        for page in sorted(connectors_dir.glob("*.md")):
            if page not in expected:
                if args.check:
                    stale.append(f"{page.relative_to(ROOT)} (no longer generated)")
                else:
                    page.unlink()
                    print(f"removed {page.relative_to(ROOT)}")
    if stale:
        print("Generated documentation is stale; run `make docs-generate`:", file=sys.stderr)
        for item in stale:
            print(f"  {item}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
