apiVersion: v1
kind: Service
metadata:
  name: {{ include "interlock.fullname" . }}-gateway
  labels:
    {{- include "interlock.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.gateway.service.pgPort }}
      targetPort: pg
      protocol: TCP
      name: pg
  selector:
    {{- include "interlock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
