apiVersion: v2
name: interlock
description: InterLock secure agent-to-data runtime proxy
version: 1.0.0-rc.18
appVersion: "1.0.0-rc.18"
type: application
home: https://github.com/ContextData/interlock
sources:
  - https://github.com/ContextData/interlock
maintainers:
  - name: ContextData
    url: https://github.com/ContextData
