"""The documentation site: generated pages current, every page reachable and tidy."""

from __future__ import annotations

import json
import re
import subprocess
import sys

import pytest
import yaml

from tests.unit.docs_site import CONTENT, ROOT, SITE, all_pages, split

GENERATOR = ROOT / "tools" / "docs" / "generate.py"


def test_generated_reference_pages_are_current() -> None:
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    assert result.returncode == 0, result.stderr


@pytest.mark.parametrize("path", all_pages(), ids=lambda p: str(p.relative_to(CONTENT)))
def test_every_page_has_a_title_and_description(path) -> None:  # type: ignore[no-untyped-def]
    meta, _ = split(path)
    assert str(meta.get("title") or "").strip(), "missing title"
    assert str(meta.get("description") or "").strip(), "missing description"


@pytest.mark.parametrize("path", all_pages(), ids=lambda p: str(p.relative_to(CONTENT)))
def test_pages_use_no_em_dashes(path) -> None:  # type: ignore[no-untyped-def]
    assert "—" not in path.read_text(encoding="utf-8")


def test_every_page_is_in_the_sidebar() -> None:
    sidebar = json.loads((SITE / "sidebar.json").read_text())
    directories = set()
    slugs = set()

    def walk(items: list[dict]) -> None:
        for item in items:
            if "autogenerate" in item:
                directories.add(item["autogenerate"]["directory"])
            if "slug" in item:
                slugs.add(item["slug"])
            if "items" in item:
                walk(item["items"])

    walk(sidebar)
    orphans = []
    for path in all_pages():
        rel = path.relative_to(CONTENT)
        if rel.parts == ("index.mdx",) or rel.parts == ("index.md",):
            continue
        slug = str(rel.with_suffix("")).removesuffix("/index")
        if rel.parts[0] not in directories and slug not in slugs:
            orphans.append(str(rel))
    assert not orphans, f"pages missing from the sidebar: {orphans}"


def test_generated_pages_say_so() -> None:
    for path in all_pages():
        meta, text = split(path)
        if meta.get("generated"):
            assert "Generated by tools/docs/generate.py" in text, path


@pytest.mark.parametrize("path", all_pages(), ids=lambda p: str(p.relative_to(CONTENT)))
def test_pages_cite_no_private_identifiers(path) -> None:  # type: ignore[no-untyped-def]
    text = path.read_text(encoding="utf-8")
    for pattern in (
        r"/Users/",
        r"contextdata\.dev",
        r"actualize-server",
        r"test-mysql",
        r"claims-test1",
        r"gmail\.com",
        r"\bAVNS_",
        r"\bdop_v1_",
        r"\bghp_[A-Za-z0-9]{10,}",
        r"\bxox[bp]-\d",
    ):
        assert not re.search(pattern, text), f"{pattern} in {path.relative_to(ROOT)}"


def test_docs_site_dependencies_are_exact_pins() -> None:
    package = json.loads((SITE / "package.json").read_text())
    for name, version in package["dependencies"].items():
        assert re.fullmatch(r"\d+\.\d+\.\d+", version), f"{name} is not pinned exactly"
    assert (SITE / "package-lock.json").exists()


def test_every_package_says_what_it_is_for() -> None:
    """The codebase map is generated from these docstrings."""
    import ast

    missing = [
        init.parent.name
        for init in sorted((ROOT / "src" / "interlock").glob("*/__init__.py"))
        if not ast.get_docstring(ast.parse(init.read_text(encoding="utf-8")))
    ]
    assert not missing, f"packages without a docstring: {missing}"


def test_ports_page_matches_the_compose_file() -> None:
    compose = yaml.safe_load((ROOT / "docker-compose.yml").read_text())
    page = (CONTENT / "reference" / "ports-and-endpoints.md").read_text()
    for service, container_port in (
        ("gateway", "3000"),
        ("gateway", "5432"),
        ("admin", "9090"),
        ("postgres", "5432"),
        ("redis", "6379"),
    ):
        mappings = [str(p) for p in compose["services"][service]["ports"]]
        host = next(m.split(":")[-2] for m in mappings if m.endswith(f":{container_port}"))
        assert f"| `{container_port}` | `{host}` |" in page, (service, container_port, host)


def test_every_documentation_path_cited_in_code_exists() -> None:
    """Code comments and docstrings that cite a page must cite one that exists."""
    cited = set()
    for root in ("src", "tests", "deploy", "tools", ".github"):
        for path in (ROOT / root).rglob("*"):
            if path.suffix not in {".py", ".yaml", ".yml", ".sh", ".md"} or not path.is_file():
                continue
            for match in re.finditer(
                r"docs-site/src/content/docs/[\w/.-]+\.mdx?", path.read_text(errors="ignore")
            ):
                cited.add(match.group(0))
    assert cited, "expected code to cite documentation pages"
    missing = sorted(c for c in cited if not (ROOT / c).exists())
    assert not missing, f"cited pages that do not exist: {missing}"


def test_the_npm_lockfile_has_a_version_for_every_package() -> None:
    """A lockfile written on one platform once carried version-less stubs for
    another platform's optional packages; npm on Linux then failed `npm ci` with
    `Invalid Version`. Regenerate the lockfile on Linux if this fails."""
    lock = json.loads((SITE / "package-lock.json").read_text())
    stubs = [path for path, meta in lock["packages"].items() if path and "version" not in meta]
    assert not stubs, f"lockfile entries without a version: {stubs}"
